AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Tarius: CFN Template to create am IAM Role for Lambda Function

Metadata:
  TemplateName: iam-role-stack.yaml
  TemplateType: IAM Role / IAM Policy
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Tarius
  Modification History:
    - 1.0.0  - May 16, 2023   -- Initial Version 
  Resources: 
    - IAM Role
    - IAM Policy Attached To The Role
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label: 
        default: "Project And Environment:"
      Parameters: 
        - ProjectName
        - Environment
    #################################### KMS Key ###################################################
    - Label: 
        default: "KMS Configuration:"
      Parameters: 
      - KmsMasterKeyId
    #################################### S3 Bucket #################################################
    - Label: 
        default: "Landing Zone S3 Bucket:"
      Parameters:
        - S3LandingZoneBucketBaseName
    #################################### Lambda Function ###########################################
    - Label:
        default: "Lambda Function:"
      Parameters:
      - LambdaFunctionBaseName
      - LambdaExecutionRoleName
      - LambdaExecutionPolicyName
    #################################### DynamoDB Table ############################################
    - Label: 
        default: "DynamoDB Configuration:"
      Parameters: 
      - DynamoDBTableBaseName
    #################################### SNS Topic #################################################
    - Label: 
        default: "SNS Topic:"
      Parameters: 
        - SNSTopicBaseName
    ################################## SQS Queue #################################################
    - Label: 
        default: "SQS Queue:"
      Parameters: 
        - SQSQueueBaseName
    ParameterLabels:
      ########################################### Project Name and Environment #######################
      ProjectName:
        default: "Project Name."
      Environment:
        default: "Environment Name."
      ################################## Lambda Function ###########################################
      LambdaFunctionBaseName:
        default: "The Base Name Of The Lambda Function."
      LambdaExecutionRoleName: 
        default: "Lambda Function Execution Role Name."
      LambdaExecutionPolicyName:
        default: "Lambda Function Execution Policy Name."
      ################################## DynamoDB Table ############################################
      DynamoDBTableBaseName: 
        default: "DynamoDB Table Base Name."
      ################################## SNS Topic #################################################
      SNSTopicBaseName:
        default: "SNS Topic Base Name."
      ################################## SQS Queue #################################################
      SQSQueueBaseName:
        default: "SQS Queue Base Name."
Parameters:
  ################## Project Name and Environment ##################################################
  ProjectName:
    Default: tarius
    Description: "The Project Name."
    Type: String
    MinLength: 4
    MaxLength: 30
    AllowedPattern: "[a-z]*"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets."
  Environment:
    Default: devl
    Description: "The Environment Name."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"
  ###################################### KMS #######################################################
  KmsMasterKeyId:
    Default: "e4c733c5-9fbe-4a90-bda1-6f0362bc9b89"
    Description: "The KMS Key Id Used For Encryption."
    Type: String
    MinLength: 36
    MaxLength: 36
    AllowedPattern: "[a-z0-9-]*"
    ConstraintDescription: "The length of the KMS Key Id should be 36 and must be lowercase alphabets, numbers and dash."
  ###################################### S3 Bucket #################################################
  S3LandingZoneBucketBaseName:
    Default: s3-bucket-base-name
    Description: "The S3 Bucket Base Name For The Source Data. The Region And Environment Will Be Added As Suffix By The Template."
    Type: String
    MinLength: 3
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: "The length should be between 3 and 40, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  ##################################### Lambda Function ###########################################
  LambdaFunctionBaseName:
    Default: some-lambda-function-name
    Description: Lambda Function Name Base Name
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 10 and 40, must contain only alphanumeric or dash.
  LambdaExecutionRoleName:
    Default: lambda-function-role-name
    Description: Lambda Function Execution Role Name
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 20 and 60, must contain only alphanumeric or dash.
  LambdaExecutionPolicyName:
    Default: policy-name
    Description: Lambda Function Execution Policy Name
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 20 and 60, must contain only alphanumeric or dash.
  ###################################### DynamoDB Stream ###########################################
  DynamoDBTableBaseName:
    Default: arn:aws:dynamodb:us-east-1:111111111111:table/dynamodb-table-name
    Description: "The Arn Of The DynamoDB Table."
    Type: String
    MinLength: 20
    MaxLength: 200
    ConstraintDescription: "The length should be between 20 and 200, must contain only lowercase letter, number, dash and should start with a letter."
  ###################################### SNS Topic #################################################
  SNSTopicBaseName:
    Default: "tarius-sns-topic"
    Description: "The Base Name Of The Sns Topic. The Region And Environment Will Be Added As Suffix By The Template."
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-]*"
    ConstraintDescription: "The length should be between 10 and 40, must contain only lowercase letter, number, dash, dot and should start with a letter."
  ###################################### SQS Queue #################################################
  SQSQueueBaseName:
    Default: "tarius-sqs-queue"
    Description: "The Base Name Of The Sns Topic. The Region And Environment Will Be Added As Suffix By The Template."
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-]*"
    ConstraintDescription: "The length should be between 10 and 40, must contain only lowercase letter, number, dash, dot and should start with a letter."
Resources:
  ###################################### Lambda Execution Role #####################################
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref LambdaExecutionRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: !Ref LambdaExecutionPolicyName
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: AllowCloudWatchLogStream
              Effect: Allow
              Action: 
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${LambdaFunctionBaseName}-${Environment}-${AWS::Region}:*'
            - Sid: AllowDynamoDBBatchWriteItem
              Effect: Allow
              Action: 
                - dynamodb:GetItem
                - dynamodb:PutItem
              Resource:
                - !Sub 'arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTableBaseName}-${Environment}-${AWS::Region}'
            - Sid: AllowSNSPublishMessage
              Effect: Allow
              Action: 
                - sns:Publish
              Resource:
                - !Sub 'arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:${SNSTopicBaseName}-${Environment}-${AWS::Region}'
            - Sid: AllowSQSSendMessage
              Effect: Allow
              Action: 
                - sqs:SendMessage
              Resource:
                - !Sub 'arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:${SQSQueueBaseName}-${Environment}-${AWS::Region}'
            - Sid: AllowReadAccessToS3Bucket
              Effect: Allow
              Action: 
                - s3:GetObject
              Resource: !Sub 'arn:${AWS::Partition}:s3:::${S3LandingZoneBucketBaseName}-${Environment}-${AWS::Region}/raw-data/*'
            - Sid: AllowWriteAccessToS3Bucket
              Effect: Allow
              Action: 
                - s3:PutObject
              Resource: !Sub 'arn:${AWS::Partition}:s3:::${S3LandingZoneBucketBaseName}-${Environment}-${AWS::Region}/invalid-records/*'
            - Sid: AllowKMSDecryption
              Effect: Allow
              Action: 
                - kms:Decrypt
                - kms:Encrypt
                - kms:GenerateDataKey
                - kms:GenerateDataKeyPair
              Resource:
                - !Sub 'arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${KmsMasterKeyId}'
      Tags: 
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key:  Environment
          Value: !Ref Environment
Outputs:
  LambdaExecutionRoleArn:
    Description: The Arn of the Lambda Execution Role
    Value: !GetAtt LambdaExecutionRole.Arn
